language: csharp
solution: "./name-sorter.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./name-sorter.sln
script:
- xbuild ./name-sorter.sln
# - mono ./Fibonacci/packages/xunit.runner.console*/tools/xunit.console.exe ./Fibonacci/Fibonacci.Tests/bin/Debug/Fibonacci.Tests.dll